sonar.projectKey=ids_ml_hospital
sonar.projectName=IDS ML Hospital
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,design/**,prototypes/**,docs/**,database/**,**/*.ipynb
sonar.coverage.exclusions=tests/**,src/app/views/**,src/app/styles/**

