[theme]
base = "light"
primaryColor = "#0058be"
backgroundColor = "#f8f9ff"
secondaryBackgroundColor = "#eff4ff"
textColor = "#0b1c30"

[client]
toolbarMode = "viewer"

[server]
headless = true

[browser]
gatherUsageStats = false
